version: 0.1
# Configuración del equipo
team: 
  name: "Integrations"
  members:
    - github: "jorgecabane"  # Username de GitHub
      slack: "U07QU7B1D46"   # User ID de Slack 
    - github: "knarf20"      # Username de GitHub
      slack: "U07QU7B1D46"   # User ID de Slack 

# Configuración de GitHub
github:  
  # Configuración de asignación automática
  auto_assign:
    enabled: true
    reviewers_per_pr: 1
    # Estrategia de asignación: "round-robin", "random", "least-busy"
    assignment_strategy: "round-robin"
    # Excluir autores del PR de la asignación
    exclude_authors: true

# Configuración de notificaciones
notifications:
  
  # Configuración de notificaciones de nuevos PRs
  new_pr_notifications:
    enabled: true
    channel: "C0ABFQMFQA0"  # Canal donde se publica el nuevo PR
    # Incluir información adicional en el mensaje
    include_reviewers: true
    include_assignees: true
    include_description: true
    include_labels: true
  
  # Configuración de reminders diarios (mensajes directos a cada persona donde haya sido asignado un PR como reviewer)
  # Nota: La hora y frecuencia se configuran en el cron job externo (Vercel/GCP)
  daily_reminders:
    enabled: true
    # Mensaje directo a cada persona con sus PRs pendientes de revisar
    message_type: "dm"  # "dm" para mensaje directo
  
  # Configuración de blame (PRs antiguos)
  # Nota: La hora y frecuencia se configuran en el cron job externo (Vercel/GCP)
  blame:
    enabled: true
    # Canal donde se publica el blame
    channel: "C0ABFQMFQA0"
    # Días después de los cuales se considera un PR "antiguo"
    after_days: 2

# Reglas generales
rules:
  # Excluir PRs con ciertos labels del proceso automático
  exclude_labels:
    - "draft"
    - "wip"
    - "do-not-review"
  
  # Incluir solo PRs con ciertos labels (opcional, si está vacío incluye todos)
  include_labels: []
